### ISSUE TITLE
快速排序那里是不是写错了？

### ISSUE THREAD

**Issue by doubleJJJJ** [josercc/iOS-Interview#2]
![WX20230928-155135@2x](https://github.com/josercc/iOS-Interview/assets/12195436/acb956af-ffe6-4ca2-9c77-af29d21fca5a)
这里的描述和图解好像对不上

**Comment by josercc** [comment]
没问题呀，一个从左侧找大于 8 就只有 12，一个从右侧查找小于 8 就是最后一个 1，两个互换位置呀

**Comment by doubleJJJJ** [comment]
> 没问题呀，一个从左边找大于8就只有12，一个从右边找小于8就是最后一个1，两个互相位置呀

文字描述是8和1交换位置，但是图解是12和1交换位置，这里有点不明白

**Comment by josercc** [comment]
> > 没问题呀，一个从左边找大于8就只有12，一个从右边找小于8就是最后一个1，两个互相位置呀
> 
> 文字描述是8和1交换位置，但是图解是12和1交换位置，这里有点不明白

那应该是写错了 感谢指正
